services:
  evkin:
    build:
      context: ../..
      dockerfile: docker/production/Dockerfile
    image: evkin-builder:production
    # entrypoint: php artisan octane:frankenphp --port=80 --host=0.0.0.0
    depends_on:
      - redis
    ports:
      - "8083:80"
    network_mode: bridge
    env_file:
      - .env.production
    restart: unless-stopped
    volumes:
      - evkin_storage:/var/www/html/storage
      - evkin_bootstrap_cache:/var/www/html/bootstrap/cache
    deploy:
      resources:
        limits:
          memory: 256M
    healthcheck:
      test: ["CMD", "php", "artisan", "octane:status", "--no-interaction"]
      interval: 30s
      timeout: 10s
      retries: 3

  worker:
    image: evkin-builder:production
    depends_on:
      - evkin
      - redis
    # command: ["sh", "-c", "php artisan queue:work --tries=3 --timeout=90 --sleep=3 --max-jobs=1000"]
    entrypoint: ["sh", "-c", "php artisan queue:work --tries=3 --timeout=90 --sleep=3 --max-jobs=1000"]
    restart: unless-stopped
    network_mode: bridge
    env_file:
      - .env.production
    environment:
      - OCTANE_SERVER=frankenphp
    volumes:
      - evkin_storage:/var/www/html/storage
      - evkin_bootstrap_cache:/var/www/html/bootstrap/cache
    deploy:
      resources:
        limits:
          memory: 256M
    healthcheck:
      test: ["CMD", "pgrep", "-f", "queue:work"]
      interval: 30s
      timeout: 10s
      retries: 3


  redis:
    image: 'redis:alpine'
    # ports:
    #   - '${FORWARD_REDIS_PORT:-6379}:6379'
    volumes:
      - 'evkin_redis:/data'
    network_mode: bridge
    healthcheck:
      test:
          - CMD
          - redis-cli
          - ping
      retries: 3
      timeout: 5s

volumes:
  evkin_storage:
  evkin_bootstrap_cache:
  evkin_redis:
