services:
  evkin:
    build:
      context: ../..
      dockerfile: docker/production/Dockerfile
    image: evkin-builder:production
    # entrypoint: php artisan octane:frankenphp --port=80 --host=0.0.0.0
    depends_on:
      - redis
    ports:
      - "8083:80"
    network_mode: bridge
    env_file:
      - .env.production
    restart: unless-stopped
    volumes:
      - evkin_storage:/var/www/html
    deploy:
      resources:
        limits:
          memory: 256M

  worker:
    image: evkin-builder:production
    depends_on:
      - evkin
      - redis
    command: ["sh", "-lc", "php artisan queue:work --tries=3 --timeout=90"]
    restart: unless-stopped
    network_mode: bridge
    environment:
      APP_ENV: production
      APP_DEBUG: "false"
    volumes:
      - evkin_storage:/var/www/html
    deploy:
      resources:
        limits:
          memory: 256M

  redis:
    image: 'redis:alpine'
    # ports:
    #   - '${FORWARD_REDIS_PORT:-6379}:6379'
    volumes:
      - 'evkin_redis:/data'
    network_mode: bridge
    healthcheck:
      test:
          - CMD
          - redis-cli
          - ping
      retries: 3
      timeout: 5s

volumes:
  evkin_storage:
  evkin_redis:
